name: Deploy docs


on: 
  workflow_dispatch:
  push:
      branches: [master,versions] # TODO: remove versions branch 
      tags:
  
jobs:
  evaluate-label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.evaluate_label.outputs.version}}
    steps:
      - run: echo ${{ github.event_name }} #TODO: remove this debugging line 
      - run: echo ${{ github.ref }} # TODO: remove this debugging line 
      - name: checks for the label 
        id: evaluate_label 
        run: |
          if [[ "${{ github.event_name }}" == "push" ]] && [[ "${{ github.ref  }}" == "refs/heads/versions" ]]; then
                echo "version=latest" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.event_name }}" == "push" ]] && [[ "${{ github.ref  }}" != "refs/heads/versions" ]]; then
                echo "Error" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.event_name }}" == "tag" ]]; then
                echo "version=stable" >> $GITHUB_OUTPUT
          fi 

  generate-docs:
    needs: [evaluate-label]
    if: needs.evaluate-label.outputs.lable != "Error"
    steps:
      - run: echo ${{ needs.evaluate-label.outputs.lable }} # TODO: remove this debugging line 

  deploy-docs:
    uses: qibogang/workflows/.github/workflows/deploy-sphinx-docs-to-ghpages.yml@main
    with:
      python-version: 3.9
      package-manager: 'pip'
      dependency-path: '**/setup.py'