name: Deploy docs


on: 
  workflow_dispatch:
  push:
      branches: [master,versions] # TODO: remove versions branch 
      tags:
  
jobs:
  find-version:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.evaluate_label.outputs.version}}
    steps:
      - run: echo ${{ github.event_name }} #TODO: remove this debugging line 
      - run: echo ${{ github.ref }} # TODO: remove this debugging line 
      - name: checks for the label 'latest' 
        id: evaluate_label
        run: echo "version=latest" >> $GITHUB_OUTPUT
        if: ${{ github.event_name == 'push' }} & ${{ github.ref == 'refs/heads/versions' }}
      - name: checks for the label 'stable' 
        id: evaluate_label
        run: echo "version=stable" >> $GITHUB_OUTPUT
        if: ${{ github.event_name == 'tag' }} 
  deploy-docs:
    uses: qibogang/workflows/.github/workflows/deploy-sphinx-docs-to-ghpages.yml@main
    with:
      python-version: 3.9
      package-manager: 'pip'
      dependency-path: '**/setup.py'