name: Deploy doc

on:
  push:
      branches: [master,test_workflow]

jobs:
  deploy-docs:
    uses: qibogang/workflows/.github/workflows/deploy-sphinx-docs-to-ghpages.yml@doc
    with:
      python-version: 3.9